version: '3.8'
services: 
    app:
      build : .
      volumes: 
        - .:/django
      ports: 
        - 8000:8000
      image: app:django
      container_name: django_container
      user: $DOCKER_USER
      command: python3  manage.py runserver 0.0.0.0:8000

 